"""Public API for quantitative signal diagnostics and validation."""

from lacuna import (
    adapters,
    bias,
    bundle,
    costs,
    cv,
    diagnostics,
    events,
    experiment,
    labels,
    plugins,
    regime,
    robustness,
    signal,
    validation,
)
from lacuna._version import __version__
from lacuna.audit import (
    Applicability,
    ApplicabilityState,
    AuditContext,
    AuditRule,
    audit,
    default_rules,
    run_audit,
)
from lacuna.audit_profiles import (
    AuditProfile,
    AuditScope,
    EvidenceDisposition,
    EvidenceRequirement,
    run_standard_audit,
    standard_audit,
    standard_profile,
)
from lacuna.benchmark import (
    BenchmarkCase,
    BenchmarkConfig,
    BenchmarkSuite,
    benchmark_config_for_tier,
    run_benchmarks,
)
from lacuna.bundle import (
    BUNDLE_FORMAT,
    BUNDLE_VERSION,
    BundleArtifact,
    BundleManifest,
    BundleVerification,
    create_bundle,
    verify_bundle,
)
from lacuna.config import Config, config, configure, get_config
from lacuna.diagnostics import (
    DIAGNOSTIC_VERSION,
    DiagnosticCheck,
    DiagnosticState,
    InstallationDiagnostics,
    diagnose_installation,
)
from lacuna.events import EventWindowResult
from lacuna.exceptions import (
    ConfigurationError,
    DataContractError,
    LacunaError,
    MethodContractError,
    NativeExtensionError,
    PluginError,
    ReportError,
)
from lacuna.experiment import ExperimentRegistry
from lacuna.labels import LabelResult
from lacuna.report import AuditReport
from lacuna.signal import BucketSpec, PortfolioProjectionResult, SignalTransformResult
from lacuna.study import SignalStudy
from lacuna.types import AnalysisResult, Finding, FindingState, ResultMetadata, Severity

__all__ = [
    "BUNDLE_FORMAT",
    "BUNDLE_VERSION",
    "DIAGNOSTIC_VERSION",
    "AnalysisResult",
    "Applicability",
    "ApplicabilityState",
    "AuditContext",
    "AuditProfile",
    "AuditReport",
    "AuditRule",
    "AuditScope",
    "BenchmarkCase",
    "BenchmarkConfig",
    "BenchmarkSuite",
    "BucketSpec",
    "BundleArtifact",
    "BundleManifest",
    "BundleVerification",
    "Config",
    "ConfigurationError",
    "DataContractError",
    "DiagnosticCheck",
    "DiagnosticState",
    "EventWindowResult",
    "EvidenceDisposition",
    "EvidenceRequirement",
    "ExperimentRegistry",
    "Finding",
    "FindingState",
    "InstallationDiagnostics",
    "LabelResult",
    "LacunaError",
    "MethodContractError",
    "NativeExtensionError",
    "PluginError",
    "PortfolioProjectionResult",
    "ReportError",
    "ResultMetadata",
    "Severity",
    "SignalStudy",
    "SignalTransformResult",
    "__version__",
    "adapters",
    "audit",
    "benchmark_config_for_tier",
    "bias",
    "bundle",
    "config",
    "configure",
    "costs",
    "create_bundle",
    "cv",
    "default_rules",
    "diagnose_installation",
    "diagnostics",
    "events",
    "experiment",
    "get_config",
    "labels",
    "plugins",
    "regime",
    "robustness",
    "run_audit",
    "run_benchmarks",
    "run_standard_audit",
    "signal",
    "standard_audit",
    "standard_profile",
    "validation",
    "verify_bundle",
]
